apiVersion: v1
baseDomain: magsolutions.us
controlPlane: 
  hyperthreading: Enabled   
  name: master
  platform:
    azure:
      osDisk:
        diskSizeGB: 1024 
      type: Standard_D8s_v3
  replicas: 3
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    azure:
      type: Standard_D2s_v3
      osDisk:
        diskSizeGB: 512 
      zones: 
      - "1"
      - "2"
      - "3"
  replicas: 2
metadata:
  name: test-cluster 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    region: usgovvirginia
    baseDomainResourceGroupName: openshift_cluster 
    networkResourceGroupName: sandbox1-openshift-network 
    virtualNetwork: sandbox1-openshift-vnet 
    controlPlaneSubnet: master 
    computeSubnet: worker 
    outboundType: UserDefinedRouting 
    cloudName: AzureUSGovernmentCloud
pullSecret: '{"auths":...replace with pullSecret content...}' 
fips: false 
sshKey: ...replace with SSH key... 
publish: Internal 