name: 'Terraform'

on:
 workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Terraform Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "./Templates/entsvcs/k8s/aks"
          tf_actions_comment: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "./Templates/entsvcs/k8s/aks"
          tf_actions_comment: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "./Templates/entsvcs/k8s/aks"
          tf_actions_comment: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "./Templates/entsvcs/k8s/aks"
          tf_actions_comment: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
          TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
      - name: "Terraform Apply"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: "./Templates/entsvcs/k8s/aks"
          tf_actions_comment: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
          TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}